# Project-wide Gradle settings.

# Enable AndroidX support
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true

# JVM Options for Gradle daemon
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Non-blocking parallel builds
org.gradle.parallel=true
